name: 'dbt_monitoring_test'
version: '1.0.0'
config-version: 2

profile: 'dbt_monitoring_test'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  environment: "dev"
  data_source: "sample"
  
models:
  dbt_monitoring_test:
    staging:
      +materialized: view
    marts:
      +materialized: table
